# Generated by Django 6.0.2 on 2026-02-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
