# Generated by Django 6.0.1 on 2026-02-22 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ideas', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.TextField()),
                ('tech_stack', models.CharField(max_length=300)),
                ('screenshots', models.ImageField(blank=True, null=True, upload_to='project_screenshots/')),
                ('documentation', models.FileField(blank=True, null=True, upload_to='project_docs/')),
                ('evaluated_marks', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('final_idea', models.ForeignKey(limit_choices_to={'status': 'approved'}, on_delete=django.db.models.deletion.CASCADE, to='ideas.idea')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='teams.team')),
            ],
        ),
    ]
