# Generated by Django 6.0.2 on 2026-03-22 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_project_github_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="screenshots",
        ),
        migrations.AddField(
            model_name="project",
            name="demo_video",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ProjectScreenshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="project_screenshots/")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screenshots_list",
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
