# Generated by Django 6.0.2 on 2026-03-23 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_project_evaluation_coding_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("revision", "Needs Revision"),
                    ("approved", "Approved"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
