# Generated by Django 6.0.2 on 2026-03-24 18:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0006_alter_project_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="batch_year",
            field=models.IntegerField(default=2026),
        ),
        migrations.AddField(
            model_name="project",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_projects", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
