# Generated by Django 6.0.2 on 2026-02-22 16:56

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ideas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="idea",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=384, null=True
            ),
        ),
        migrations.AddField(
            model_name="idea",
            name="similarity_score",
            field=models.FloatField(default=0.0),
        ),
    ]
