# Generated by Django 6.0.2 on 2026-03-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ideas", "0002_idea_embedding_idea_similarity_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="idea",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
    ]
