# Generated by Django 6.0.2 on 2026-03-30 19:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ideas", "0003_idea_remarks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="idea",
            name="description",
        ),
    ]
