# Generated by Django 6.0.2 on 2026-03-22 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
        ('teams', '0002_alter_team_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='team',
        ),
        migrations.AddField(
            model_name='notice',
            name='teams',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
    ]
