# Generated by Django 6.0.2 on 2026-03-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_remove_notice_team_notice_teams'),
        ('teams', '0002_alter_team_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='teams',
        ),
        migrations.AddField(
            model_name='notice',
            name='teams',
            field=models.ManyToManyField(blank=True, null=True, to='teams.team'),
        ),
    ]
