# Generated by Django 6.0.2 on 2026-03-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notices", "0003_remove_notice_teams_notice_teams"),
        ("teams", "0002_alter_team_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notice",
            name="teams",
            field=models.ManyToManyField(blank=True, to="teams.team"),
        ),
    ]
