# Generated by Django 6.0.1 on 2026-02-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projectInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('title', models.CharField(default='Unknown', max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('abstract', models.TextField()),
                ('team_member1', models.CharField(max_length=100)),
                ('team_member2', models.CharField(max_length=100)),
                ('team_member3', models.CharField(max_length=100)),
                ('team_member4', models.CharField(max_length=100)),
                ('project_guide', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
