# Generated by Django 6.0.2 on 2026-03-30 19:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Showcase", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectinfo",
            name="description",
        ),
    ]
