# Generated by Django 5.2.12 on 2026-03-31 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Showcase', '0002_remove_projectinfo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
